kind: pipeline
name: default

steps:
- name: build
  image: node:lts
  environment:
    WEBHOOK_URL:
      from_secret: slack_webhook_url
    TARGET_DATE:
      from_secret: target_date
  commands:
  - npm install
  - node list-reservable-date-of-Shirokane-Zensou.js
  #- node list-reservable-date-of-Shirokane-Zensou.js > result.txt
  #- if [ cat result.txt | grep "$TARGET_DATE" > /dev/null ]; then curl -X POST -H 'Content-type: application/json' --data '{"text":"Reservable now"}' "$WEBHOOK_URL" fi


