name: ubuntu

on:
  schedule:
  - cron: 35 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run script
      run: node list-reservable-date-of-Shirokane-Zensou.js
